# 
#  base n Dockerfile.humble_nvidia
#  rename tag to pov:humble
FROM pov:humble

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
   && apt-get -y install --no-install-recommends \
    tmux \
    tmuxp \
    psmisc \
    htop \
    ros-humble-rmw-cyclonedds-cpp \
    python3-colcon-clean \
    xclip \
    ros-humble-mavros \
    ros-humble-mavros-extras \
    python3-colcon-clean \
   #  python3-opencv \
    ros-humble-cv-bridge \
    ros-humble-rosbridge-suite \
      libgstreamer1.0-0 \
      gstreamer1.0-plugins-base \
      gstreamer1.0-plugins-good \
      gstreamer1.0-plugins-bad \
      gstreamer1.0-plugins-ugly \
      gstreamer1.0-tools \
      python3-gi \
      gir1.2-gstreamer-1.0 \
      libgstreamer-plugins-base1.0-dev \
      gstreamer1.0-libav \
      gstreamer-1.0 \
      #rqt
      ros-humble-rqt \
      ros-humble-qt-gui \
      ros-humble-rqt-tf-tree \
      ros-humble-rqt-reconfigure \
      #
      ros-humble-async-web-server-cpp \
      ros-humble-vision-msgs \
      ros-humble-image-view \
      ros-humble-vision-msgs-rviz-plugins \
      ros-humble-vision-msgs-rviz-plugins \
      #
      python3-serial \
      libgz-sim8-dev \
      rapidjson-dev \
      #
      ros-humble-tf-transformations \
   && apt-get autoremove -y \
   && apt-get clean -y \
   && rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=dialog

# Set up auto-source of workspace for ros user
ARG WORKSPACE
COPY .devcontainer/.tmux.conf /etc/tmux.conf

RUN ros2 run mavros install_geographiclib_datasets.sh

# install mavproxy and other python packages as user
USER user
RUN python3 -m pip install --user MAVProxy

ENV PATH="/home/user/.local/bin:$PATH"

COPY .devcontainer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt