- gz_topic_name: "/model/vehicle_blue/odometry"
  ros_topic_name: "sim_odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
- gz_topic_name: "/imu"
  ros_topic_name: "sim_imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
- gz_topic_name: "/cmd_vel"
  ros_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
- gz_topic_name: "/world/Moving_robot/clock"
  ros_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
- gz_topic_name: "/model/vehicle_blue/tf"
  ros_topic_name: "tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  