- gz_topic_name: "clock"
  ros_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
- gz_topic_name: "model/rover/odometry"
  ros_topic_name: "sim_odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
- gz_topic_name: "/camera"
  ros_topic_name: "/gz_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
- gz_topic_name: "/camera_info"
  ros_topic_name: "/gz_camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"