#
# node:
/mavros/**:
  ros__parameters:
    startup_px4_usb_quirk: false

# --- system plugins ---
/mavros/**/vision_pose:
  ros__parameters:
    use_sim_time: true
    
# sys_status & sys_time connection options
/mavros/**/conn:
  ros__parameters:
    heartbeat_rate: 1.0    # send heartbeat rate in Hertz
    heartbeat_mav_type: "ONBOARD_CONTROLLER"
    timeout: 10.0          # heartbeat timeout in seconds
    timesync_rate: 10.0    # TIMESYNC rate in Hertz (feature disabled if 0.0)
    system_time_rate: 1.0  # send system time to FCU rate in Hertz (disabled if 0.0)

# sys_status
/mavros/**/sys:
  ros__parameters:
    min_voltage: [10.0]   # diagnostics min voltage, use a vector i.e. [16.2, 16.0] for multiple batteries, up-to 10 are supported
                        # to achieve the same on a ROS launch file do: <rosparam param="sys/min_voltage">[16.2, 16.0]</rosparam>
    disable_diag: false # disable all sys_status diagnostics, except heartbeat

# sys_time
/mavros/**/time:
  ros__parameters:
    time_ref_source: "fcu"  # time_reference source
    timesync_mode: MAVLINK
    timesync_avg_alpha: 0.6 # timesync averaging factor

# setpoint_attitude
/mavros/**/setpoint_attitude:
  ros__parameters:
    reverse_thrust: false     # allow reversed thrust
    use_quaternion: true
    
/mavros/**/setpoint_raw:
  ros__parameters:
    thrust_scaling: 1.0

/mavros/**/imu:
  ros__parameters:
    frame_id: "base_link"
    # need find actual values
    linear_acceleration_stdev: 0.0003
    angular_velocity_stdev: 0.0003490659 # 0.02 degrees
    orientation_stdev: 1.0
    magnetic_stdev: 0.0